export const FETCH_CAT_FACTS = 'FETCH_CAT_FACTS';
export const FETCH_CAT_FACTS_BEGIN = 'FETCH_CAT_FACTS_BEGIN';
export const FETCH_CAT_FACTS_SUCCESS = 'FETCH_CAT_FACTS_SUCCESS';
export const FETCH_CAT_FACTS_ERROR = 'FETCH_CAT_FACTS_ERROR';
